### ISSUE TITLE
Avoiding 'execute' command

### ISSUE THREAD

**Issue by pmallas** [mankoff/kdm-idl#3]
Hello, 

I found an instance where the exeucte command is used, and can be replaced (since in some instances the 'execute' command is not allowed):

In kdm_define:
ok =  Execute("struct = {" + Obj_Class(self) + "}")
can be replaced with 
struct = create_struct(name = Obj_Class(self))

Anyway, just a suggestion.

**Comment by mankoff** [comment]
Fixed in f0fe702 but untested until I get GDL working on OS X...
